### ISSUE TITLE
How to use assembler.py ?

### ISSUE THREAD

**Issue by tesths** [sarsanaee/Simple-C-Compiler#1]
Now I have a threeaddresscode text file.
Just like
```
1: t0 := 1
2: t1 := 4
3: t2 := t0 * 3
4: t2 := t2 + t1
5: t3 := -12
6: t4 := t2 * 8
7: t5 := 1.900000
8: t3[t4] := t5
9: param n
10: call SYSIN,1
11: t6 := 1
12: i := t6
13: t7 := n
14: goto 16
```
I try to use your python script as `python python.py`, but it print something below.
```
% 1: =  %  :=
% 2: =  %  :=
% 5: =  %  :=
% 7: =  %  :=
% 8: =  %  :=
% 11: =  %  :=
% 12: =  %  :=
% 13: =  %  :=
% 17: =  %  :=
% 22: =  %  :=
% 27: =  %  :=
% 29: =  %  :=
% 30: =  %  :=
```
What's the problem?

**Comment by sarsanaee** [comment]
Thank you for your contact,

If you run the bash file available in the project a simple three address
code is generated called "outfile". I think your three address code is not
in the same style of the sample. Furthermore, there was a problem in the
assembler which is now OK.

And this assembler was not developed for all of the LLVM primitives but a limited number of them, if you need more primitive instruction then you should develop them I guess.

**Comment by tesths** [comment]
Thanks for your help!
